-- Question 1 - Which are the top 3 relevant elements of the Solar System?
SELECT SUM(ELEMENT_COMPOSITION.ELEMENT_QUANTITY) AS TOTAL_QUANTITY, ELEMENTS.ELEMENT_DESCRIPTION 
FROM ELEMENT_COMPOSITION
LEFT JOIN ELEMENTS ON ELEMENT_COMPOSITION.ELEMENT_ID = ELEMENTS.ELEMENT_ID
GROUP BY ELEMENT_COMPOSITION.ELEMENT_ID
ORDER BY TOTAL_QUANTITY DESC
LIMIT 3;

/* Question 2 - At a maximum constant speed of 40.000 km/h, show how much time it
would take for the Apollo 10 mission, to make a round trip from the
earth to each of the other planets (the table has distance from sun).*/

SELECT SUM(DISTANCE_TO_EARTH) * 2 * 150000000 / 40000
FROM PLANETS;


-- Question 3 - Calculate solar system's total mass not including the black matter.
SELECT SUM(PLANET_WEIGHT) AS TOTAL_MASS
FROM (
	SELECT PLANET_WEIGHT FROM PLANET_METRICS 
	UNION ALL
	SELECT DWARF_PLANETS_WEIGHT FROM DWARF_PLANETS 
	UNION ALL
	SELECT STAR_WEIGHT FROM STARS 
	UNION ALL
	SELECT MOON_WEIGHT FROM MOONS) AS ALL_OBJECTS;

-- Question 4 - Which planet has the minimum number of rotation days per revolution.

SELECT PLANET_NAME, DAYS_OF_ROTATION / DAYS_OF_REVOLUTION AS RATIO
FROM PLANETS
WHERE DAYS_OF_ROTATION / DAYS_OF_REVOLUTION = (SELECT MIN(DAYS_OF_ROTATION / DAYS_OF_REVOLUTION) FROM PLANETS)

-- Question 5 - which planet/object has the highest percentage of the most popular element relative to mass?

WITH TMP as (
SELECT (EL_QTY / PLANET_WEIGHT) AS RATIO, PLANET_METRICS_ID
FROM (
	SELECT PLANET_METRICS_ID, PLANET_WEIGHT, 
		(SELECT ELEMENT_QUANTITY FROM ELEMENT_COMPOSITION, PLANETS
		WHERE PLANET_METRICS.PLANET_METRICS_ID = PLANETS.PLANET_METRICS_ID
		AND ELEMENT_COMPOSITION.ELEMENT_COMPOSITION_ID = PLANETS.ELEMENT_COMPOSITION_ID
		AND ELEMENT_COMPOSITION.ELEMENT_id = 'H') AS EL_QTY
    FROM PLANET_METRICS 
	UNION ALL
	SELECT DWARF_PLANET_NAME, DWARF_PLANETS_WEIGHT, 
			(SELECT ELEMENT_QUANTITY FROM ELEMENT_COMPOSITION  
            WHERE ELEMENT_COMPOSITION.ELEMENT_COMPOSITION_ID = DWARF_PLANETS.ELEMENT_COMPOSITION_ID
            AND ELEMENT_COMPOSITION.ELEMENT_ID = 'H') 
	FROM DWARF_PLANETS
	UNION ALL
	SELECT STAR_NAME, STAR_WEIGHT,
			(SELECT ELEMENT_QUANTITY FROM ELEMENT_COMPOSITION  
            WHERE ELEMENT_COMPOSITION.ELEMENT_COMPOSITION_ID = STARS.ELEMENT_COMPOSITION_ID
            AND ELEMENT_COMPOSITION.ELEMENT_ID = 'H') 
    FROM STARS 
) AS ALL_OBJECTS)
SELECT PLANET_METRICS_ID AS OBJECT_NAME, RATIO FROM TMP
WHERE RATIO = (SELECT MAX(RATIO) FROM TMP);




